/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as StorefrontRouteImport } from './routes/_storefront'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as StorefrontIndexRouteImport } from './routes/_storefront/index'
import { Route as StorefrontAccountRouteImport } from './routes/_storefront/_account'
import { Route as StorefrontAboutRouteImport } from './routes/_storefront/about'
import { Route as StorefrontCartRouteImport } from './routes/_storefront/cart'
import { Route as StorefrontCategoriesRouteImport } from './routes/_storefront/categories'
import { Route as StorefrontCheckoutRouteImport } from './routes/_storefront/checkout'
import { Route as StorefrontContactRouteImport } from './routes/_storefront/contact'
import { Route as StorefrontFaqRouteImport } from './routes/_storefront/faq'
import { Route as StorefrontPrivacyPolicyRouteImport } from './routes/_storefront/privacy-policy'
import { Route as StorefrontReturnsRouteImport } from './routes/_storefront/returns'
import { Route as StorefrontServicesRouteImport } from './routes/_storefront/services'
import { Route as StorefrontShopRouteImport } from './routes/_storefront/shop'
import { Route as StorefrontTermsRouteImport } from './routes/_storefront/terms'
import { Route as StorefrontWarrantyRouteImport } from './routes/_storefront/warranty'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminBusinessRouteImport } from './routes/_admin/admin.business'
import { Route as AdminAdminCategoriesRouteImport } from './routes/_admin/admin.categories'
import { Route as AdminAdminCustomersRouteImport } from './routes/_admin/admin.customers'
import { Route as AdminAdminDeliveryRouteImport } from './routes/_admin/admin.delivery'
import { Route as AdminAdminFaqsRouteImport } from './routes/_admin/admin.faqs'
import { Route as AdminAdminHomepageRouteImport } from './routes/_admin/admin.homepage'
import { Route as AdminAdminInventoryRouteImport } from './routes/_admin/admin.inventory'
import { Route as AdminAdminMessagesRouteImport } from './routes/_admin/admin.messages'
import { Route as AdminAdminOrdersRouteImport } from './routes/_admin/admin.orders'
import { Route as AdminAdminPoliciesRouteImport } from './routes/_admin/admin.policies'
import { Route as AdminAdminProductsRouteImport } from './routes/_admin/admin.products'
import { Route as AdminAdminServicesRouteImport } from './routes/_admin/admin.services'
import { Route as StorefrontAccountAccountRouteImport } from './routes/_storefront/_account/account'
import { Route as StorefrontAccountOrdersRouteImport } from './routes/_storefront/_account/orders'
import { Route as StorefrontAccountLoginRouteImport } from './routes/_storefront/account.login'
import { Route as StorefrontAccountRegisterRouteImport } from './routes/_storefront/account.register'
import { Route as StorefrontCategorySlugRouteImport } from './routes/_storefront/category.$slug'
import { Route as StorefrontOrderConfirmationIdRouteImport } from './routes/_storefront/order-confirmation.$id'
import { Route as StorefrontProductSlugRouteImport } from './routes/_storefront/product.$slug'
import { Route as StorefrontServiceSlugRouteImport } from './routes/_storefront/service.$slug'
import { Route as AdminAdminOrdersIndexRouteImport } from './routes/_admin/admin.orders.index'
import { Route as AdminAdminOrdersIdRouteImport } from './routes/_admin/admin.orders.$id'
import { Route as AdminAdminProductsIndexRouteImport } from './routes/_admin/admin.products.index'
import { Route as AdminAdminProductsIdRouteImport } from './routes/_admin/admin.products.$id'
import { Route as AdminAdminProductsNewRouteImport } from './routes/_admin/admin.products.new'
import { Route as StorefrontAccountOrdersIdRouteImport } from './routes/_storefront/_account/orders.$id'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StorefrontRoute = StorefrontRouteImport.update({
  id: '/_storefront',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const StorefrontIndexRoute = StorefrontIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontAccountRoute = StorefrontAccountRouteImport.update({
  id: '/_account',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontAboutRoute = StorefrontAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontCartRoute = StorefrontCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontCategoriesRoute = StorefrontCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontCheckoutRoute = StorefrontCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontContactRoute = StorefrontContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontFaqRoute = StorefrontFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontPrivacyPolicyRoute = StorefrontPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontReturnsRoute = StorefrontReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontServicesRoute = StorefrontServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontShopRoute = StorefrontShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontTermsRoute = StorefrontTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontWarrantyRoute = StorefrontWarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => StorefrontRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminBusinessRoute = AdminAdminBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCategoriesRoute = AdminAdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCustomersRoute = AdminAdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminDeliveryRoute = AdminAdminDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminFaqsRoute = AdminAdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminHomepageRoute = AdminAdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminInventoryRoute = AdminAdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminMessagesRoute = AdminAdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminOrdersRoute = AdminAdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPoliciesRoute = AdminAdminPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminProductsRoute = AdminAdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminServicesRoute = AdminAdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminAdminRoute,
} as any)
const StorefrontAccountAccountRoute =
  StorefrontAccountAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => StorefrontAccountRoute,
  } as any)
const StorefrontAccountOrdersRoute = StorefrontAccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StorefrontAccountRoute,
} as any)
const StorefrontAccountLoginRoute = StorefrontAccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontAccountRegisterRoute =
  StorefrontAccountRegisterRouteImport.update({
    id: '/account/register',
    path: '/account/register',
    getParentRoute: () => StorefrontRoute,
  } as any)
const StorefrontCategorySlugRoute = StorefrontCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontOrderConfirmationIdRoute =
  StorefrontOrderConfirmationIdRouteImport.update({
    id: '/order-confirmation/$id',
    path: '/order-confirmation/$id',
    getParentRoute: () => StorefrontRoute,
  } as any)
const StorefrontProductSlugRoute = StorefrontProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => StorefrontRoute,
} as any)
const StorefrontServiceSlugRoute = StorefrontServiceSlugRouteImport.update({
  id: '/service/$slug',
  path: '/service/$slug',
  getParentRoute: () => StorefrontRoute,
} as any)
const AdminAdminOrdersIndexRoute = AdminAdminOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminOrdersRoute,
} as any)
const AdminAdminOrdersIdRoute = AdminAdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAdminOrdersRoute,
} as any)
const AdminAdminProductsIndexRoute = AdminAdminProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminProductsRoute,
} as any)
const AdminAdminProductsIdRoute = AdminAdminProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAdminProductsRoute,
} as any)
const AdminAdminProductsNewRoute = AdminAdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminAdminProductsRoute,
} as any)
const StorefrontAccountOrdersIdRoute =
  StorefrontAccountOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => StorefrontAccountOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof StorefrontIndexRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/about': typeof StorefrontAboutRoute
  '/cart': typeof StorefrontCartRoute
  '/categories': typeof StorefrontCategoriesRoute
  '/checkout': typeof StorefrontCheckoutRoute
  '/contact': typeof StorefrontContactRoute
  '/faq': typeof StorefrontFaqRoute
  '/privacy-policy': typeof StorefrontPrivacyPolicyRoute
  '/returns': typeof StorefrontReturnsRoute
  '/services': typeof StorefrontServicesRoute
  '/shop': typeof StorefrontShopRoute
  '/terms': typeof StorefrontTermsRoute
  '/warranty': typeof StorefrontWarrantyRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/business': typeof AdminAdminBusinessRoute
  '/admin/categories': typeof AdminAdminCategoriesRoute
  '/admin/customers': typeof AdminAdminCustomersRoute
  '/admin/delivery': typeof AdminAdminDeliveryRoute
  '/admin/faqs': typeof AdminAdminFaqsRoute
  '/admin/homepage': typeof AdminAdminHomepageRoute
  '/admin/inventory': typeof AdminAdminInventoryRoute
  '/admin/messages': typeof AdminAdminMessagesRoute
  '/admin/orders': typeof AdminAdminOrdersRouteWithChildren
  '/admin/policies': typeof AdminAdminPoliciesRoute
  '/admin/products': typeof AdminAdminProductsRouteWithChildren
  '/admin/services': typeof AdminAdminServicesRoute
  '/account': typeof StorefrontAccountAccountRoute
  '/orders': typeof StorefrontAccountOrdersRouteWithChildren
  '/account/login': typeof StorefrontAccountLoginRoute
  '/account/register': typeof StorefrontAccountRegisterRoute
  '/category/$slug': typeof StorefrontCategorySlugRoute
  '/order-confirmation/$id': typeof StorefrontOrderConfirmationIdRoute
  '/product/$slug': typeof StorefrontProductSlugRoute
  '/service/$slug': typeof StorefrontServiceSlugRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/orders/$id': typeof AdminAdminOrdersIdRoute
  '/admin/products/$id': typeof AdminAdminProductsIdRoute
  '/admin/products/new': typeof AdminAdminProductsNewRoute
  '/orders/$id': typeof StorefrontAccountOrdersIdRoute
  '/admin/orders/': typeof AdminAdminOrdersIndexRoute
  '/admin/products/': typeof AdminAdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof StorefrontIndexRoute
  '/about': typeof StorefrontAboutRoute
  '/cart': typeof StorefrontCartRoute
  '/categories': typeof StorefrontCategoriesRoute
  '/checkout': typeof StorefrontCheckoutRoute
  '/contact': typeof StorefrontContactRoute
  '/faq': typeof StorefrontFaqRoute
  '/privacy-policy': typeof StorefrontPrivacyPolicyRoute
  '/returns': typeof StorefrontReturnsRoute
  '/services': typeof StorefrontServicesRoute
  '/shop': typeof StorefrontShopRoute
  '/terms': typeof StorefrontTermsRoute
  '/warranty': typeof StorefrontWarrantyRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/business': typeof AdminAdminBusinessRoute
  '/admin/categories': typeof AdminAdminCategoriesRoute
  '/admin/customers': typeof AdminAdminCustomersRoute
  '/admin/delivery': typeof AdminAdminDeliveryRoute
  '/admin/faqs': typeof AdminAdminFaqsRoute
  '/admin/homepage': typeof AdminAdminHomepageRoute
  '/admin/inventory': typeof AdminAdminInventoryRoute
  '/admin/messages': typeof AdminAdminMessagesRoute
  '/admin/policies': typeof AdminAdminPoliciesRoute
  '/admin/services': typeof AdminAdminServicesRoute
  '/account': typeof StorefrontAccountAccountRoute
  '/orders': typeof StorefrontAccountOrdersRouteWithChildren
  '/account/login': typeof StorefrontAccountLoginRoute
  '/account/register': typeof StorefrontAccountRegisterRoute
  '/category/$slug': typeof StorefrontCategorySlugRoute
  '/order-confirmation/$id': typeof StorefrontOrderConfirmationIdRoute
  '/product/$slug': typeof StorefrontProductSlugRoute
  '/service/$slug': typeof StorefrontServiceSlugRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/orders/$id': typeof AdminAdminOrdersIdRoute
  '/admin/products/$id': typeof AdminAdminProductsIdRoute
  '/admin/products/new': typeof AdminAdminProductsNewRoute
  '/orders/$id': typeof StorefrontAccountOrdersIdRoute
  '/admin/orders': typeof AdminAdminOrdersIndexRoute
  '/admin/products': typeof AdminAdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_storefront': typeof StorefrontRouteWithChildren
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_storefront/_account': typeof StorefrontAccountRouteWithChildren
  '/_storefront/about': typeof StorefrontAboutRoute
  '/_storefront/cart': typeof StorefrontCartRoute
  '/_storefront/categories': typeof StorefrontCategoriesRoute
  '/_storefront/checkout': typeof StorefrontCheckoutRoute
  '/_storefront/contact': typeof StorefrontContactRoute
  '/_storefront/faq': typeof StorefrontFaqRoute
  '/_storefront/privacy-policy': typeof StorefrontPrivacyPolicyRoute
  '/_storefront/returns': typeof StorefrontReturnsRoute
  '/_storefront/services': typeof StorefrontServicesRoute
  '/_storefront/shop': typeof StorefrontShopRoute
  '/_storefront/terms': typeof StorefrontTermsRoute
  '/_storefront/warranty': typeof StorefrontWarrantyRoute
  '/admin/login': typeof AdminLoginRoute
  '/_storefront/': typeof StorefrontIndexRoute
  '/_admin/admin/business': typeof AdminAdminBusinessRoute
  '/_admin/admin/categories': typeof AdminAdminCategoriesRoute
  '/_admin/admin/customers': typeof AdminAdminCustomersRoute
  '/_admin/admin/delivery': typeof AdminAdminDeliveryRoute
  '/_admin/admin/faqs': typeof AdminAdminFaqsRoute
  '/_admin/admin/homepage': typeof AdminAdminHomepageRoute
  '/_admin/admin/inventory': typeof AdminAdminInventoryRoute
  '/_admin/admin/messages': typeof AdminAdminMessagesRoute
  '/_admin/admin/orders': typeof AdminAdminOrdersRouteWithChildren
  '/_admin/admin/policies': typeof AdminAdminPoliciesRoute
  '/_admin/admin/products': typeof AdminAdminProductsRouteWithChildren
  '/_admin/admin/services': typeof AdminAdminServicesRoute
  '/_storefront/_account/account': typeof StorefrontAccountAccountRoute
  '/_storefront/_account/orders': typeof StorefrontAccountOrdersRouteWithChildren
  '/_storefront/account/login': typeof StorefrontAccountLoginRoute
  '/_storefront/account/register': typeof StorefrontAccountRegisterRoute
  '/_storefront/category/$slug': typeof StorefrontCategorySlugRoute
  '/_storefront/order-confirmation/$id': typeof StorefrontOrderConfirmationIdRoute
  '/_storefront/product/$slug': typeof StorefrontProductSlugRoute
  '/_storefront/service/$slug': typeof StorefrontServiceSlugRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/orders/$id': typeof AdminAdminOrdersIdRoute
  '/_admin/admin/products/$id': typeof AdminAdminProductsIdRoute
  '/_admin/admin/products/new': typeof AdminAdminProductsNewRoute
  '/_storefront/_account/orders/$id': typeof StorefrontAccountOrdersIdRoute
  '/_admin/admin/orders/': typeof AdminAdminOrdersIndexRoute
  '/_admin/admin/products/': typeof AdminAdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy-policy'
    | '/returns'
    | '/services'
    | '/shop'
    | '/terms'
    | '/warranty'
    | '/admin/login'
    | '/admin/business'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/delivery'
    | '/admin/faqs'
    | '/admin/homepage'
    | '/admin/inventory'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/policies'
    | '/admin/products'
    | '/admin/services'
    | '/account'
    | '/orders'
    | '/account/login'
    | '/account/register'
    | '/category/$slug'
    | '/order-confirmation/$id'
    | '/product/$slug'
    | '/service/$slug'
    | '/admin/'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/orders/$id'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy-policy'
    | '/returns'
    | '/services'
    | '/shop'
    | '/terms'
    | '/warranty'
    | '/admin/login'
    | '/admin/business'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/delivery'
    | '/admin/faqs'
    | '/admin/homepage'
    | '/admin/inventory'
    | '/admin/messages'
    | '/admin/policies'
    | '/admin/services'
    | '/account'
    | '/orders'
    | '/account/login'
    | '/account/register'
    | '/category/$slug'
    | '/order-confirmation/$id'
    | '/product/$slug'
    | '/service/$slug'
    | '/admin'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/orders/$id'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/_admin'
    | '/_storefront'
    | '/_admin/admin'
    | '/_storefront/_account'
    | '/_storefront/about'
    | '/_storefront/cart'
    | '/_storefront/categories'
    | '/_storefront/checkout'
    | '/_storefront/contact'
    | '/_storefront/faq'
    | '/_storefront/privacy-policy'
    | '/_storefront/returns'
    | '/_storefront/services'
    | '/_storefront/shop'
    | '/_storefront/terms'
    | '/_storefront/warranty'
    | '/admin/login'
    | '/_storefront/'
    | '/_admin/admin/business'
    | '/_admin/admin/categories'
    | '/_admin/admin/customers'
    | '/_admin/admin/delivery'
    | '/_admin/admin/faqs'
    | '/_admin/admin/homepage'
    | '/_admin/admin/inventory'
    | '/_admin/admin/messages'
    | '/_admin/admin/orders'
    | '/_admin/admin/policies'
    | '/_admin/admin/products'
    | '/_admin/admin/services'
    | '/_storefront/_account/account'
    | '/_storefront/_account/orders'
    | '/_storefront/account/login'
    | '/_storefront/account/register'
    | '/_storefront/category/$slug'
    | '/_storefront/order-confirmation/$id'
    | '/_storefront/product/$slug'
    | '/_storefront/service/$slug'
    | '/_admin/admin/'
    | '/_admin/admin/orders/$id'
    | '/_admin/admin/products/$id'
    | '/_admin/admin/products/new'
    | '/_storefront/_account/orders/$id'
    | '/_admin/admin/orders/'
    | '/_admin/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  StorefrontRoute: typeof StorefrontRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_storefront': {
      id: '/_storefront'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StorefrontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_storefront/': {
      id: '/_storefront/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StorefrontIndexRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/_account': {
      id: '/_storefront/_account'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StorefrontAccountRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/about': {
      id: '/_storefront/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof StorefrontAboutRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/cart': {
      id: '/_storefront/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof StorefrontCartRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/categories': {
      id: '/_storefront/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof StorefrontCategoriesRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/checkout': {
      id: '/_storefront/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof StorefrontCheckoutRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/contact': {
      id: '/_storefront/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof StorefrontContactRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/faq': {
      id: '/_storefront/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof StorefrontFaqRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/privacy-policy': {
      id: '/_storefront/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof StorefrontPrivacyPolicyRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/returns': {
      id: '/_storefront/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof StorefrontReturnsRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/services': {
      id: '/_storefront/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof StorefrontServicesRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/shop': {
      id: '/_storefront/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof StorefrontShopRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/terms': {
      id: '/_storefront/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof StorefrontTermsRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/warranty': {
      id: '/_storefront/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof StorefrontWarrantyRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/business': {
      id: '/_admin/admin/business'
      path: '/business'
      fullPath: '/admin/business'
      preLoaderRoute: typeof AdminAdminBusinessRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/categories': {
      id: '/_admin/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminAdminCategoriesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/customers': {
      id: '/_admin/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminAdminCustomersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/delivery': {
      id: '/_admin/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminAdminDeliveryRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/faqs': {
      id: '/_admin/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminAdminFaqsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/homepage': {
      id: '/_admin/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminAdminHomepageRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/inventory': {
      id: '/_admin/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminAdminInventoryRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/messages': {
      id: '/_admin/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminAdminMessagesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/orders': {
      id: '/_admin/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAdminOrdersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/policies': {
      id: '/_admin/admin/policies'
      path: '/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AdminAdminPoliciesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/products': {
      id: '/_admin/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAdminProductsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/services': {
      id: '/_admin/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminAdminServicesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_storefront/_account/account': {
      id: '/_storefront/_account/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof StorefrontAccountAccountRouteImport
      parentRoute: typeof StorefrontAccountRoute
    }
    '/_storefront/_account/orders': {
      id: '/_storefront/_account/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof StorefrontAccountOrdersRouteImport
      parentRoute: typeof StorefrontAccountRoute
    }
    '/_storefront/account/login': {
      id: '/_storefront/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof StorefrontAccountLoginRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/account/register': {
      id: '/_storefront/account/register'
      path: '/account/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof StorefrontAccountRegisterRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/category/$slug': {
      id: '/_storefront/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof StorefrontCategorySlugRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/order-confirmation/$id': {
      id: '/_storefront/order-confirmation/$id'
      path: '/order-confirmation/$id'
      fullPath: '/order-confirmation/$id'
      preLoaderRoute: typeof StorefrontOrderConfirmationIdRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/product/$slug': {
      id: '/_storefront/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof StorefrontProductSlugRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_storefront/service/$slug': {
      id: '/_storefront/service/$slug'
      path: '/service/$slug'
      fullPath: '/service/$slug'
      preLoaderRoute: typeof StorefrontServiceSlugRouteImport
      parentRoute: typeof StorefrontRoute
    }
    '/_admin/admin/orders/': {
      id: '/_admin/admin/orders/'
      path: '/'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminAdminOrdersIndexRouteImport
      parentRoute: typeof AdminAdminOrdersRoute
    }
    '/_admin/admin/orders/$id': {
      id: '/_admin/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminAdminOrdersIdRouteImport
      parentRoute: typeof AdminAdminOrdersRoute
    }
    '/_admin/admin/products/': {
      id: '/_admin/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminAdminProductsIndexRouteImport
      parentRoute: typeof AdminAdminProductsRoute
    }
    '/_admin/admin/products/$id': {
      id: '/_admin/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminAdminProductsIdRouteImport
      parentRoute: typeof AdminAdminProductsRoute
    }
    '/_admin/admin/products/new': {
      id: '/_admin/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminAdminProductsNewRouteImport
      parentRoute: typeof AdminAdminProductsRoute
    }
    '/_storefront/_account/orders/$id': {
      id: '/_storefront/_account/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof StorefrontAccountOrdersIdRouteImport
      parentRoute: typeof StorefrontAccountOrdersRoute
    }
  }
}

interface AdminAdminOrdersRouteChildren {
  AdminAdminOrdersIdRoute: typeof AdminAdminOrdersIdRoute
  AdminAdminOrdersIndexRoute: typeof AdminAdminOrdersIndexRoute
}

const AdminAdminOrdersRouteChildren: AdminAdminOrdersRouteChildren = {
  AdminAdminOrdersIdRoute: AdminAdminOrdersIdRoute,
  AdminAdminOrdersIndexRoute: AdminAdminOrdersIndexRoute,
}

const AdminAdminOrdersRouteWithChildren =
  AdminAdminOrdersRoute._addFileChildren(AdminAdminOrdersRouteChildren)

interface AdminAdminProductsRouteChildren {
  AdminAdminProductsIdRoute: typeof AdminAdminProductsIdRoute
  AdminAdminProductsNewRoute: typeof AdminAdminProductsNewRoute
  AdminAdminProductsIndexRoute: typeof AdminAdminProductsIndexRoute
}

const AdminAdminProductsRouteChildren: AdminAdminProductsRouteChildren = {
  AdminAdminProductsIdRoute: AdminAdminProductsIdRoute,
  AdminAdminProductsNewRoute: AdminAdminProductsNewRoute,
  AdminAdminProductsIndexRoute: AdminAdminProductsIndexRoute,
}

const AdminAdminProductsRouteWithChildren =
  AdminAdminProductsRoute._addFileChildren(AdminAdminProductsRouteChildren)

interface AdminAdminRouteChildren {
  AdminAdminBusinessRoute: typeof AdminAdminBusinessRoute
  AdminAdminCategoriesRoute: typeof AdminAdminCategoriesRoute
  AdminAdminCustomersRoute: typeof AdminAdminCustomersRoute
  AdminAdminDeliveryRoute: typeof AdminAdminDeliveryRoute
  AdminAdminFaqsRoute: typeof AdminAdminFaqsRoute
  AdminAdminHomepageRoute: typeof AdminAdminHomepageRoute
  AdminAdminInventoryRoute: typeof AdminAdminInventoryRoute
  AdminAdminMessagesRoute: typeof AdminAdminMessagesRoute
  AdminAdminOrdersRoute: typeof AdminAdminOrdersRouteWithChildren
  AdminAdminPoliciesRoute: typeof AdminAdminPoliciesRoute
  AdminAdminProductsRoute: typeof AdminAdminProductsRouteWithChildren
  AdminAdminServicesRoute: typeof AdminAdminServicesRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminBusinessRoute: AdminAdminBusinessRoute,
  AdminAdminCategoriesRoute: AdminAdminCategoriesRoute,
  AdminAdminCustomersRoute: AdminAdminCustomersRoute,
  AdminAdminDeliveryRoute: AdminAdminDeliveryRoute,
  AdminAdminFaqsRoute: AdminAdminFaqsRoute,
  AdminAdminHomepageRoute: AdminAdminHomepageRoute,
  AdminAdminInventoryRoute: AdminAdminInventoryRoute,
  AdminAdminMessagesRoute: AdminAdminMessagesRoute,
  AdminAdminOrdersRoute: AdminAdminOrdersRouteWithChildren,
  AdminAdminPoliciesRoute: AdminAdminPoliciesRoute,
  AdminAdminProductsRoute: AdminAdminProductsRouteWithChildren,
  AdminAdminServicesRoute: AdminAdminServicesRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StorefrontAccountOrdersRouteChildren {
  StorefrontAccountOrdersIdRoute: typeof StorefrontAccountOrdersIdRoute
}

const StorefrontAccountOrdersRouteChildren: StorefrontAccountOrdersRouteChildren =
  {
    StorefrontAccountOrdersIdRoute: StorefrontAccountOrdersIdRoute,
  }

const StorefrontAccountOrdersRouteWithChildren =
  StorefrontAccountOrdersRoute._addFileChildren(
    StorefrontAccountOrdersRouteChildren,
  )

interface StorefrontAccountRouteChildren {
  StorefrontAccountAccountRoute: typeof StorefrontAccountAccountRoute
  StorefrontAccountOrdersRoute: typeof StorefrontAccountOrdersRouteWithChildren
}

const StorefrontAccountRouteChildren: StorefrontAccountRouteChildren = {
  StorefrontAccountAccountRoute: StorefrontAccountAccountRoute,
  StorefrontAccountOrdersRoute: StorefrontAccountOrdersRouteWithChildren,
}

const StorefrontAccountRouteWithChildren =
  StorefrontAccountRoute._addFileChildren(StorefrontAccountRouteChildren)

interface StorefrontRouteChildren {
  StorefrontAccountRoute: typeof StorefrontAccountRouteWithChildren
  StorefrontAboutRoute: typeof StorefrontAboutRoute
  StorefrontCartRoute: typeof StorefrontCartRoute
  StorefrontCategoriesRoute: typeof StorefrontCategoriesRoute
  StorefrontCheckoutRoute: typeof StorefrontCheckoutRoute
  StorefrontContactRoute: typeof StorefrontContactRoute
  StorefrontFaqRoute: typeof StorefrontFaqRoute
  StorefrontPrivacyPolicyRoute: typeof StorefrontPrivacyPolicyRoute
  StorefrontReturnsRoute: typeof StorefrontReturnsRoute
  StorefrontServicesRoute: typeof StorefrontServicesRoute
  StorefrontShopRoute: typeof StorefrontShopRoute
  StorefrontTermsRoute: typeof StorefrontTermsRoute
  StorefrontWarrantyRoute: typeof StorefrontWarrantyRoute
  StorefrontIndexRoute: typeof StorefrontIndexRoute
  StorefrontAccountLoginRoute: typeof StorefrontAccountLoginRoute
  StorefrontAccountRegisterRoute: typeof StorefrontAccountRegisterRoute
  StorefrontCategorySlugRoute: typeof StorefrontCategorySlugRoute
  StorefrontOrderConfirmationIdRoute: typeof StorefrontOrderConfirmationIdRoute
  StorefrontProductSlugRoute: typeof StorefrontProductSlugRoute
  StorefrontServiceSlugRoute: typeof StorefrontServiceSlugRoute
}

const StorefrontRouteChildren: StorefrontRouteChildren = {
  StorefrontAccountRoute: StorefrontAccountRouteWithChildren,
  StorefrontAboutRoute: StorefrontAboutRoute,
  StorefrontCartRoute: StorefrontCartRoute,
  StorefrontCategoriesRoute: StorefrontCategoriesRoute,
  StorefrontCheckoutRoute: StorefrontCheckoutRoute,
  StorefrontContactRoute: StorefrontContactRoute,
  StorefrontFaqRoute: StorefrontFaqRoute,
  StorefrontPrivacyPolicyRoute: StorefrontPrivacyPolicyRoute,
  StorefrontReturnsRoute: StorefrontReturnsRoute,
  StorefrontServicesRoute: StorefrontServicesRoute,
  StorefrontShopRoute: StorefrontShopRoute,
  StorefrontTermsRoute: StorefrontTermsRoute,
  StorefrontWarrantyRoute: StorefrontWarrantyRoute,
  StorefrontIndexRoute: StorefrontIndexRoute,
  StorefrontAccountLoginRoute: StorefrontAccountLoginRoute,
  StorefrontAccountRegisterRoute: StorefrontAccountRegisterRoute,
  StorefrontCategorySlugRoute: StorefrontCategorySlugRoute,
  StorefrontOrderConfirmationIdRoute: StorefrontOrderConfirmationIdRoute,
  StorefrontProductSlugRoute: StorefrontProductSlugRoute,
  StorefrontServiceSlugRoute: StorefrontServiceSlugRoute,
}

const StorefrontRouteWithChildren = StorefrontRoute._addFileChildren(
  StorefrontRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  StorefrontRoute: StorefrontRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
